### ISSUE TITLE
Сбербанк апи

### ISSUE THREAD

**Issue by Niccolum** [DiverOfDark/BudgetTracker#140]
Сможешь ли добавить историю транзакций со Сбербанком?
https://developer.sberbank.ru/doc/v1

**Comment by DiverOfDark** [comment]
По этому API - нет:
* Fintech API предназначен для работы с данными корпоративных клиентов ПАО Сбербанк.
* Подключение к Fintech API осуществляется на платной основе, на основе заявки будет рассчитана стоимость подключения.


Если бы у меня был счет в сбербанке - я бы мог реализовать это также, как это работает с другими банками - т.е. через Selenium и скачивание и разбор выписки, например:

https://github.com/DiverOfDark/BudgetTracker/blob/master/BudgetTracker/Scrapers/RaiffeisenScraper.cs

**Comment by Niccolum** [comment]
А каким образом показывается история транзакций с банков? Периодический скан страницы?

**Comment by Niccolum** [comment]
И ещё вопрос - если у меня получится реализовать это на питоне и продемонстрировать тебе - сможешь ли ты переписать это на шарп?

**Comment by DiverOfDark** [comment]
Да, периодический скан страницы.

Я бы мог переписать на шарп, но как ты думаешь - может, имеет смысл сделать API для таких случаев, что ты мог, например, поддерживать свой микросервис на питоне, который бы просто REST-ом отправлял транзакции в BT?

**Comment by Niccolum** [comment]
Тогда попробую заморочиться с селениумом, Сбербанком и питоном. Потом гистом кину сюда, не закрывай пока тикет.

По поводу внешней интеграции - можно, но зачем, если твоё приложение целостное и, впринципе, тебе не нужно получать данные извне. Мне кажется нужно дождаться прецедента, когда это понадобится и тогда думать, вместо того, чтобы делать никому не нужную функциональность

**Comment by Niccolum** [comment]
Вопрос по скрапингу.
В каком формате ты собираешь данные?
https://github.com/DiverOfDark/BudgetTracker/blob/master/BudgetTracker/Scrapers/RaiffeisenScraper.cs#L59
Тут не очень понятно.
Можешь объяснить словами?

**Comment by Niccolum** [comment]
> Да, периодический скан страницы.
> 
> Я бы мог переписать на шарп, но как ты думаешь - может, имеет смысл сделать API для таких случаев, что ты мог, например, поддерживать свой микросервис на питоне, который бы просто REST-ом отправлял транзакции в BT?

Ещё раз перечитал то, что ты написал.
Впринципе имеет смысл вынос модулей, собирающих информацию и передающую её в твой сервис, в микросервисы, вместо отдельных модулей, как у тебя сейчас.
Тогда да, попробуй написать апи, а я переведу своё добро со сбором в микросервис, как "аддон" для твоего. И проверим.
Видимо невыспался или поздно прочитал, идея нормальная. По крайней мере позволит подключить ограниченное количество таких сборщиков, а не всё вместе, как у тебя сейчас

Ник в телеграмме как и тут. Пиши, если понадоблюсь

**Comment by DiverOfDark** [comment]
Мне кажется, это правильно иметь ряд "встроенных" сборщиков, которые я мог бы поддерживать в рабочем состоянии, так и API для "сторонних" сборщиков.

Далее, какие данные понадобятся:

Для каждого из счетов:
- Название счета
- Текущая сумма средств на счете
- Валюта счета

Для каждой транзакции:
- Уникальный ID транзакции
- Название счета
- Время транзакции
- Сумма средств
- Валюта транзакции
- Текстовое описание транзакции


Сделаю API для этого случая, как раз чтобы ты мог сам поддерживать такой Сбербанк-микросервис

**Comment by Niccolum** [comment]
Увидел, что это должно быть возможно, если отключить двухфакторную авторизацию на сайте. Проверю, если нет блокировки парсеров, то сделаю и отпишусь

**Comment by Niccolum** [comment]
Не мог бы ты @DiverOfDark дать мне описание твоего апи в формате openapi, json-schema или любого другого?

**Comment by Niccolum** [comment]
По поводу транзакции:
![Снимок экрана от 2019-10-01 12-22-14](https://user-images.githubusercontent.com/32839735/65950231-549e1280-e446-11e9-9f32-1bb39a7fc302.png)
Это всё, что я смогу вытащить.

Ну и название счёта сюда, конечно

Вот другой вид, из которого тоже непонятны 
![Снимок экрана от 2019-10-01 12-24-46](https://user-images.githubusercontent.com/32839735/65950416-ae9ed800-e446-11e9-966c-6ba79217d84f.png)

- Уникальный ID транзакции

- Время транзакции (только дата)

Вопрос - если я буду генерить ID на лету - могут ли быть какие то проблемы?
Что предлагаешь делать в этой ситуации?

**Comment by DiverOfDark** [comment]
Описание API вместе с методом сделаю на днях. Не обещаю какого-то внятного описания, но посмотрю что можно сделать относительно недорого. В худшем случае - просто текстовое описание русским по белому. Сейчас есть некоторая глобальная проблема по всему github actions, который используется для сборки проекта, с тем что на нем перестали работать .net core билды из-за апдейта linux kernel.

Это статистика по вкладам, интереснее видеть статистику по операциям по счету.
Время можно считать за 00:00:00, это не страшно
IP - можно генерировать, но это должен быть устойчивый ID. Например, ```SHA1(Time+Name+Sum+Ccy)```

**Comment by Niccolum** [comment]
Хорошо, такой кейс:
отправляю тебе пачку данных 2 раза в день
утром была совершена транзакция, которая попадает в обе отправки
Сейчас, при текущем видении, т.к. ID генерится на лету - это будут разные ID транзакций (т.к. минимальный срок выборки - день), но одна и та же транзакция.
Получается, этот ID транзакции если и сгенерирован, то должен быть постоянно привязан к одной транзакции. А это значит мне надо будет всё класть в локальную базку (Думаю, возьму sqlite), чтобы ID не повторялись и не было отправленных дублей.
Я ведь прав?

Ну, или сделать ID, зависимый от входящих параметров

**Comment by Niccolum** [comment]
Я думаю, id будет действительно зависимым от входящих параметров и вида
```
>>> RawTransaction = namedtuple('BankTransaction', ['account_name', 'time', 'cost', 'currency', 'description'])
>>> Transaction = namedtuple('FullTransaction', ['id', 'transaction'])
>>> raw_tr = RawTransaction(account_name="Сберегательный счет", time='28.09.2019', cost=-50000, currency=52000, description='Частичная выдача')
>>> tr_id = uuid.uuid5(uuid.NAMESPACE_X500, repr(raw_tr)).hex
>>> tr = Transaction(id=tr_id, transaction=raw_tr)
>>> tr
>>> Transaction(id='ce5300304f725b8a858c69fb38a48980', transaction=RawTransaction(account_name='Сберегательный счет', time='28.09.2019', cost=-50000, currency=52000, description='Частичная выдача'))
```

**Comment by DiverOfDark** [comment]
Добавил API, описание только текстом в README.MD, см. коммит. 
Попробуй подходит ли тебе.

**Comment by Niccolum** [comment]
Я ещё работаю. Скажу немного позже, но на первый взгляд вполне себе. Единственное - добавь what в единичное апи

**Comment by DiverOfDark** [comment]
Единичное API - это про текущее состояние счета, там не может быть What.

Текущий баланс счета никак не связан с транзакциями.

**Comment by Niccolum** [comment]
> Единичное API - это про текущее состояние счета, там не может быть What.
> 
> Текущий баланс счета никак не связан с транзакциями.

Увидел.
Тогда пару вопросов:
1. /post-data только добавляется или добавляется и обновляется счёт?
2. Можно сделать /get-data/<id> эндпоинт, чтобы проверять, есть ли такой счёт? Можно без подробностей, хотя бы ответ в виде була.
3. Ничего страшного не произойдёт, если я буду обновлять состояние счёта вкупе с добавлением новых транзакций? Или это разово? Или надо, но редко?

**Comment by DiverOfDark** [comment]
1) счёт создается если не существует. затем обновляется состояние счёта на указанную(текущую, если не передана) дату.
2) зачем?
3) Наоборот, это как раз и нужно делать. Изначально предполагалось что состояние счета, как и переводы, обновляются каждый день.

**Comment by Niccolum** [comment]
2. Это на случай, если ответ на п.1 был бы другой)
3. Ок

В общем, как закончу со своей стороны и протестирую взаимодействие с твоим - отпишусь. Думаю, это займёт некоторое время

**Comment by DiverOfDark** [comment]
Закрываю, т.к. нет обновлений.

**Comment by Niccolum** [comment]
https://github.com/Niccolum/py_parse_sber
Закончил около месяца назад
Сорян, что так долго.
Всё протестировано, работает, при, описанное тут, соблюдает. Совместно с приложением, правда, не тестировалось, но уверен, что никаких проблем, если контракт не поменялся

**Comment by Niccolum** [comment]
@DiverOfDark
