### ISSUE TITLE
Интеграция с Телеграммом

### ISSUE THREAD

**Issue by Niccolum** [DiverOfDark/BudgetTracker#141]
Подскажи, собираешься ли делать интеграцию с телегой? В вашем языке вроде есть либы для общения с ним. Возможно, смогу подсобить, но я python разработчик. Только если микросервис написать для тебя по составленному плану

**Comment by DiverOfDark** [comment]
У меня не было таких планов. Интеграцию с телеграмом сделать не сложно, но лично мне не очевидны сценарии использования, можешь рассказать подробнее как себе это видишь?

**Comment by Niccolum** [comment]
Лично я себе это видел как возможность рилтайм прихода сообщений о тратах из банков в виде стандартного шаблона. Что то на подобие смс, но централизованно от твоего приложения и конкретному человеку. Минимум личных данных. Только - от кого, сколько и на что. 

Это всё как вариант, конечно. Нужно ли это твоему приложению в его текущей архитектуре или нет

**Comment by Niccolum** [comment]
Хотя, смс от банков, наверно, нивелирует это, и это не нужно. Но тут смотри сам

**Comment by DiverOfDark** [comment]
Нет, в виде риалтайм это не возможно точно - т.к. сбор данных из банков происходит раз в 4 часа.

Это мог бы быть алертинг в каком-то виде, но пока что такого не существует. 
Можно попробовать вернуться к этой идее, когда/если появится бюджетирование.
